# Generated by Django 3.1.3 on 2020-11-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USR_TIMETBL_INF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USRID', models.CharField(max_length=200)),
                ('USRNAME', models.CharField(max_length=400)),
                ('GRPID', models.CharField(max_length=200)),
                ('GRPNAME', models.CharField(max_length=200)),
                ('GRPBUNRUI', models.CharField(max_length=200)),
                ('USR_TIMEINF', models.CharField(max_length=1000)),
                ('REGDATE', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
